# Generated by Django 2.1 on 2018-12-04 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_article_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='auther',
            new_name='author',
        ),
    ]
